# Cluster Affinity Propagation

## Abrindo o arquivo de treino

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

treino = pd.read_csv('treino.csv')
treino.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 3 columns):
Classificacao    4572 non-null int64
Genero           4572 non-null int64
Plataforma       4572 non-null int64
dtypes: int64(3)
memory usage: 107.2 KB


In [2]:
treino.head()

Classificacao  Genero  Plataforma
0              1       3          14
1              0       8           4
2              2       8          14
3              2       8           4
4              0       0           9

## Treinando o modelo

In [3]:
from sklearn.cluster import AffinityPropagation
clusteringAffinityPropagation = AffinityPropagation(max_iter=600).fit(treino)

## Atributos do cluster

### cluster_centers_indices_

In [4]:
print(clusteringAffinityPropagation.cluster_centers_indices_)
print("Tamanho: " , len(clusteringAffinityPropagation.cluster_centers_indices_))

[   8   11   13 ... 4555 4566 4571]
Tamanho:  1006


### cluster_centers_

In [5]:
print(clusteringAffinityPropagation.cluster_centers_)
print("Tamanho: " , len(clusteringAffinityPropagation.cluster_centers_))

[[0 0 6]
 [1 6 4]
 [0 1 4]
 ...
 [2 3 6]
 [0 2 4]
 [0 4 0]]
Tamanho:  1006


### labels_

In [6]:
print(clusteringAffinityPropagation.labels_)
print("Tamanho: " , len(clusteringAffinityPropagation.labels_))

[ 305  581    5 ...  241  265 1005]
Tamanho:  4572


### affinity_matrix_

In [7]:
print(clusteringAffinityPropagation.affinity_matrix_)
print("Tamanho: " , len(clusteringAffinityPropagation.affinity_matrix_))

[[  -0. -126.  -26. ...  -65. -110. -198.]
 [-126.   -0. -104. ... -353.   -8.  -32.]
 [ -26. -104.   -0. ...  -89. -104. -216.]
 ...
 [ -65. -353.  -89. ...   -0. -333. -489.]
 [-110.   -8. -104. ... -333.   -0.  -24.]
 [-198.  -32. -216. ... -489.  -24.   -0.]]
Tamanho:  4572


### n_iter_

In [8]:
print(clusteringAffinityPropagation.n_iter_)

600


# Predição

### Abrindo arquivo de teste

In [9]:
teste = pd.read_csv('teste.csv')
teste.head()

Ano de lancamento  Classificacao  Contagem de criticas  \
0             1998.0              1                  20.0   
1             2010.0              2                  51.0   
2             2002.0              0                  20.0   
3             2008.0              3                  26.0   
4             2014.0              1                  46.0   

   Contagem de usuarios  Desenvolvedora  Genero  Media de pontuacao  \
0                 918.0              44       8               51.70   
1                  20.0             331       6               41.00   
2                   6.0             909       0               46.90   
3                  14.0             629       3               38.85   
4                  84.0            1272       8               23.75   

                                      Nome  Outras vendas  Plataforma  \
0                         Metal Gear Solid           0.24          12   
1  SOCOM: U.S. Navy SEALs Fireteam Bravo 3           0.08          16   
2                    World Series Baseball           0.01          13   
3           Spectrobes: Beyond the Portals           0.04           3   
4                    Yaiba: Ninja Gaiden Z           0.02           5   

   Pontuacao da critica  Pontuacao dos usuarios  Publicadora  Vendas EU  \
0                  94.0                     9.4           14       1.83   
1                  74.0                     8.0            3       0.13   
2                  85.0                     8.8            8       0.05   
3                  70.0                     7.7           32       0.11   
4                  43.0                     4.5           48       0.03   

   Vendas JP  Vendas NA  Vendas globais  
0       0.78       3.18            6.03  
1       0.06       0.17            0.44  
2       0.00       0.17            0.23  
3       0.00       0.36            0.51  
4       0.00       0.05            0.09

### Criando uma nova coluna para o agrupamento

In [10]:
def predicao(x):
    return clusteringAffinityPropagation.predict([x])[0]
teste['Agrupamento'] = teste.apply(lambda row: predicao([row['Plataforma'], row['Genero'], row['Classificacao']]), axis=1)

In [11]:
teste

Ano de lancamento  Classificacao  Contagem de criticas  \
0                1998.0              1                  20.0   
1                2010.0              2                  51.0   
2                2002.0              0                  20.0   
3                2008.0              3                  26.0   
4                2014.0              1                  46.0   
5                2008.0              2                  47.0   
6                2003.0              0                  18.0   
7                2006.0              2                  46.0   
8                2008.0              3                  15.0   
9                2006.0              2                  30.0   
10               2002.0              2                  41.0   
11               2011.0              2                  48.0   
12               2006.0              2                   4.0   
13               2012.0              0                  19.0   
14               2007.0              0                  15.0   
15               2008.0              2                  26.0   
16               2003.0              0                   9.0   
17               2015.0              2                  24.0   
18               2010.0              2                  13.0   
19               2015.0              1                  17.0   
20               2003.0              0                  27.0   
21               2013.0              0                  22.0   
22               2010.0              0                  40.0   
23               2004.0              1                  43.0   
24               2015.0              0                  12.0   
25               2008.0              2                  35.0   
26               2005.0              0                  14.0   
27               2011.0              2                  56.0   
28               2015.0              2                  28.0   
29               2013.0              3                   6.0   
...                 ...            ...                   ...   
2223             2008.0              0                   5.0   
2224             2009.0              2                   5.0   
2225             2003.0              0                   8.0   
2226             2006.0              1                  19.0   
2227             2004.0              2                  25.0   
2228             2006.0              2                  78.0   
2229             2002.0              2                  22.0   
2230             2007.0              1                  34.0   
2231             2012.0              0                  12.0   
2232             2009.0              1                  27.0   
2233             2005.0              1                  47.0   
2234             2011.0              2                  46.0   
2235             2013.0              1                  12.0   
2236             2004.0              0                  34.0   
2237             2007.0              3                  11.0   
2238             2009.0              0                  19.0   
2239             2001.0              1                   4.0   
2240             2003.0              0                  28.0   
2241             2003.0              2                  23.0   
2242             2002.0              1                  39.0   
2243             2005.0              3                   4.0   
2244             2002.0              0                  19.0   
2245             2007.0              0                  26.0   
2246             2013.0              3                  75.0   
2247             2003.0              0                  26.0   
2248             2010.0              1                  17.0   
2249             2004.0              0                  26.0   
2250             2010.0              3                   6.0   
2251             2008.0              3                  55.0   
2252             2012.0              1                  87.0   

      Contagem de usuarios  Desenvolv

In [12]:
teste.describe()

Ano de lancamento  Classificacao  Contagem de criticas  \
count        2253.000000    2253.000000           2253.000000   
mean         2007.502885       1.294274             29.040391   
std             4.153217       1.044714             19.277668   
min          1992.000000       0.000000              4.000000   
25%          2004.000000       0.000000             15.000000   
50%          2007.000000       1.000000             25.000000   
75%          2011.000000       2.000000             39.000000   
max          2016.000000       7.000000            113.000000   

       Contagem de usuarios  Desenvolvedora       Genero  Media de pontuacao  \
count           2253.000000     2253.000000  2253.000000         2253.000000   
mean             173.991567      361.807812     5.145584           38.792277   
std              557.111943      375.161642     3.343577            7.422147   
min                4.000000        0.000000     0.000000            7.000000   
25%               12.000000       69.000000     2.000000           34.600000   
50%               27.000000      226.000000     6.000000           40.000000   
75%               89.000000      537.000000     8.000000           44.250000   
max             8713.000000     1693.000000    11.000000           53.050000   

       Outras vendas   Plataforma  Pontuacao da critica  \
count    2253.000000  2253.000000           2253.000000   
mean        0.087248     8.480692             70.402130   
std         0.251000     5.622857             13.944728   
min         0.000000     0.000000             13.000000   
25%         0.010000     4.000000             62.000000   
50%         0.020000     6.000000             73.000000   
75%         0.070000    14.000000             81.000000   
max         7.530000    22.000000             98.000000   

       Pontuacao dos usuarios  Publicadora    Vendas EU    Vendas JP  \
count             2253.000000  2253.000000  2253.000000  2253.000000   
mean                 7.182423    35.633822     0.242645     0.059183   
std                  1.439358    71.842118     0.568239     0.247925   
min                  1.000000     0.000000     0.000000     0.000000   
25%                  6.500000     5.000000     0.020000     0.000000   
50%                  7.500000    10.000000     0.060000     0.000000   
75%                  8.200000    28.000000     0.220000     0.020000   
max                  9.600000   541.000000     9.200000     5.320000   

         Vendas NA  Vendas globais  Agrupamento  
count  2253.000000     2253.000000  2253.000000  
mean      0.400453        0.789720   228.328451  
std       0.808167        1.566231   153.203719  
min       0.000000        0.010000     1.000000  
25%       0.060000        0.110000    49.000000  
50%       0.150000        0.310000   294.000000  
75%       0.410000        0.800000   344.000000  
max      15.000000       21.810000   684.000000

In [13]:
a = teste['Agrupamento'].unique()

In [14]:
a.sort()
a

array([  1,   8,  12,  13,  18,  32,  44,  48,  49,  71, 104, 150, 152,
       158, 184, 232, 239, 294, 307, 344, 398, 418, 425, 470, 639, 684])

In [30]:
# Plataforma - Gênero - Classificação
# Ultra Street Fighter IV - [9,9,2]
# Dragon Ball Z: Budokai 2 - [19,9,2]
# SOCOM: U.S. Navy SEALs Fireteam Bravo 3 - [16,6,2]
# Final Fantasy XI: Treasures of Aht Urhgan - [6,3,2]
clusteringAffinityPropagation.predict([[16,6,2],[19,9,2],[9,9,2],[6,3,2]])

array([ 12, 294, 294,  18])

In [31]:
teste[teste['Agrupamento']==18]

Ano de lancamento  Classificacao  Contagem de criticas  \
3                2008.0              3                  26.0   
9                2006.0              2                  30.0   
10               2002.0              2                  41.0   
12               2006.0              2                   4.0   
17               2015.0              2                  24.0   
36               1999.0              2                   9.0   
42               1996.0              1                  12.0   
45               2006.0              2                  27.0   
46               2007.0              3                  30.0   
56               2000.0              2                  12.0   
57               2011.0              3                  26.0   
77               2004.0              2                  34.0   
96               2009.0              2                  57.0   
103              2011.0              1                  89.0   
119              2005.0              3                  64.0   
149              2000.0              2                  21.0   
151              2011.0              2                  27.0   
159              2014.0              1                  13.0   
164              2008.0              2                  22.0   
184              2005.0              2                  50.0   
198              2006.0              2                  25.0   
203              2005.0              2                  29.0   
244              2014.0              1                  59.0   
304              2003.0              2                  22.0   
307              2014.0              2                   4.0   
315              2009.0              1                  41.0   
325              2003.0              3                  29.0   
343              2010.0              1                  60.0   
347              2013.0              1                  33.0   
362              2001.0              2                   9.0   
...                 ...            ...                   ...   
1935             2014.0              2                  23.0   
1948             2005.0              2                  15.0   
1954             1999.0              2                  12.0   
1960             2007.0              2                  68.0   
1987             2002.0              2                  20.0   
1990             2010.0              2                  49.0   
2007             2005.0              3                  23.0   
2028             2001.0              1                  24.0   
2030             2002.0              2                  24.0   
2051             2006.0              2                  35.0   
2070             2002.0              2                  10.0   
2072             2010.0              2                  43.0   
2074             2006.0              2                  19.0   
2075             2000.0              2                  21.0   
2076             2008.0              2                  80.0   
2098             2009.0              3                  27.0   
2119             2007.0              1                  44.0   
2126             2006.0              3                  25.0   
2129             2000.0              2                  10.0   
2135             2008.0              2                  67.0   
2140             2009.0              2                  27.0   
2145             2002.0              2                  26.0   
2146             2016.0              1                  18.0   
2159             2004.0              2                  25.0   
2173             2015.0              2                  26.0   
2181             2006.0              2                  33.0   
2188             2015.0              2                  35.0   
2208             2010.0              1                  14.0   
2210             2008.0              2                  34.0   
2219             2006.0              2                  40.0   

      Contagem de usuarios  Desenvolv

In [17]:
for x in a:
    print(teste[teste['Agrupamento']==x].count())
    
# teste[teste['Agrupamento']==4].groupby(by=['Media de pontuacao'])

# print(teste[teste['Agrupamento']==5].count())

Ano de lancamento         2
Classificacao             2
Contagem de criticas      2
Contagem de usuarios      2
Desenvolvedora            2
Genero                    2
Media de pontuacao        2
Nome                      2
Outras vendas             2
Plataforma                2
Pontuacao da critica      2
Pontuacao dos usuarios    2
Publicadora               2
Vendas EU                 2
Vendas JP                 2
Vendas NA                 2
Vendas globais            2
Agrupamento               2
dtype: int64
Ano de lancamento         21
Classificacao             21
Contagem de criticas      21
Contagem de usuarios      21
Desenvolvedora            21
Genero                    21
Media de pontuacao        21
Nome                      21
Outras vendas             21
Plataforma                21
Pontuacao da critica      21
Pontuacao dos usuarios    21
Publicadora               21
Vendas EU                 21
Vendas JP                 21
Vendas NA                 21
Vendas globais     