# Cluster Affinity Propagation

## Abrindo o arquivo de treino

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

treino = pd.read_csv('treino.csv')
treino.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9575 entries, 0 to 9574
Data columns (total 3 columns):
Classificacao    9575 non-null int64
Genero           9575 non-null int64
Plataforma       9575 non-null int64
dtypes: int64(3)
memory usage: 224.5 KB


In [2]:
treino.head()

Classificacao  Genero  Plataforma
0              2       9           7
1              0      11          13
2              0       7           5
3              2       4           5
4              3       4          17

## Treinando o modelo

In [3]:
from sklearn.cluster import AffinityPropagation
clusteringAffinityPropagation = AffinityPropagation(max_iter=400).fit(treino)

## Atributos do cluster

### cluster_centers_indices_

In [4]:
print(clusteringAffinityPropagation.cluster_centers_indices_)
print("Tamanho: " , len(clusteringAffinityPropagation.cluster_centers_indices_))

[   2    4    5 ... 9570 9572 9574]
Tamanho:  4882


### cluster_centers_

In [5]:
print(clusteringAffinityPropagation.cluster_centers_)
print("Tamanho: " , len(clusteringAffinityPropagation.cluster_centers_))

[[ 0  7  5]
 [ 3  4 17]
 [ 3  9  6]
 ...
 [ 2  9  5]
 [ 0  9 16]
 [ 0 10  6]]
Tamanho:  4882


### labels_

In [6]:
print(clusteringAffinityPropagation.labels_)
print("Tamanho: " , len(clusteringAffinityPropagation.labels_))

[1250  191    0 ... 4880 1049 4881]
Tamanho:  9575


### affinity_matrix_

In [7]:
print(clusteringAffinityPropagation.affinity_matrix_)
print("Tamanho: " , len(clusteringAffinityPropagation.affinity_matrix_))

[[  -0.  -44.  -12. ...  -85.  -93.   -6.]
 [ -44.   -0.  -80. ...  -13. -221.  -50.]
 [ -12.  -80.   -0. ... -125.  -45.  -10.]
 ...
 [ -85.  -13. -125. ...   -0. -260. -101.]
 [ -93. -221.  -45. ... -260.   -0.  -97.]
 [  -6.  -50.  -10. ... -101.  -97.   -0.]]
Tamanho:  9575


### n_iter_

In [8]:
print(clusteringAffinityPropagation.n_iter_)

400


# Predição

### Abrindo arquivo de teste

In [9]:
teste = pd.read_csv('teste.csv')
teste.head()

Ano de lancamento  Classificacao  Contagem de criticas  \
0                  0              3                  19.0   
1               2008              4                  11.0   
2                  0              2                  16.0   
3               2006              0                   0.0   
4               2007              1                  21.0   

   Contagem de usuarios  Desenvolvedora  Genero  Media de pontuacao  \
0                  12.0             251       4               30.25   
1                   6.0             261      11               32.90   
2                1096.0             190       9               42.00   
3                   0.0               0      11                0.00   
4                  11.0            1398       5               38.75   

                                  Nome  Outras vendas  Plataforma  \
0                         Virtua Quest           0.00          20   
1                                 Bolt           0.02           6   
2                         Dead Space 3           0.02          15   
3  Kamaitachi no Yoru 2: Tokubetsu Hen           0.00          17   
4                    Nervous Brickdown           0.00           4   

   Pontuacao da critica  Pontuacao dos usuarios  Publicadora  Vendas EU  \
0                  55.0                     5.5           54       0.00   
1                  59.0                     6.8           33       0.04   
2                  78.0                     6.0            8       0.16   
3                   0.0                     0.0          121       0.00   
4                  70.0                     7.5           22       0.01   

   Vendas JP  Vendas NA  Vendas globais  
0       0.00       0.01            0.01  
1       0.00       0.12            0.19  
2       0.00       0.02            0.19  
3       0.01       0.00            0.01  
4       0.00       0.00            0.02

### Criando uma nova coluna para o agrupamento

In [10]:
def predicao(x):
    return clusteringAffinityPropagation.predict([x])[0]
teste['Agrupamento'] = teste.apply(lambda row: predicao([row['Plataforma'], row['Genero'], row['Classificacao']]), axis=1)

In [11]:
teste

Ano de lancamento  Classificacao  Contagem de criticas  \
0                     0              3                  19.0   
1                  2008              4                  11.0   
2                     0              2                  16.0   
3                  2006              0                   0.0   
4                  2007              1                  21.0   
5                  2001              1                  16.0   
6                  2010              0                   0.0   
7                  1998              0                   0.0   
8                  2002              1                  24.0   
9                  2010              0                   0.0   
10                 2010              2                  74.0   
11                 1995              0                   0.0   
12                 1999              0                   0.0   
13                 2008              3                  61.0   
14                 2010              1                   5.0   
15                 2010              0                   0.0   
16                 2015              0                   0.0   
17                 1994              0                   0.0   
18                 2012              0                   0.0   
19                 2011              0                   0.0   
20                 2015              0                   0.0   
21                 2007              3                  42.0   
22                    0              3                  49.0   
23                 2010              4                   6.0   
24                 2005              1                   0.0   
25                 2007              1                  19.0   
26                 2010              3                  11.0   
27                 2005              4                  22.0   
28                 2012              0                   0.0   
29                 2006              4                   7.0   
...                 ...            ...                   ...   
4687               2006              1                  30.0   
4688               2013              2                  82.0   
4689               2012              4                  44.0   
4690               2011              3                   4.0   
4691               2004              1                  20.0   
4692               2008              0                   0.0   
4693               2006              3                  19.0   
4694               2005              3                  54.0   
4695               1997              0                   0.0   
4696               2008              0                   0.0   
4697               1998              0                   0.0   
4698               2006              4                  26.0   
4699               2003              3                  24.0   
4700                  0              2                  33.0   
4701               1994              0                   0.0   
4702               2011              0                   0.0   
4703               2007              0                   0.0   
4704               2007              0                   0.0   
4705               2003              3                  26.0   
4706               2014              4                   4.0   
4707               2002              3                  23.0   
4708               2005              0                   0.0   
4709               2011              2                   7.0   
4710               2001              0                   0.0   
4711               1998              0                   0.0   
4712                  0              3                  26.0   
4713               2004              1                  35.0   
4714               2013              2                   5.0   
4715               2009              0                   0.0   
4716               2011              0                   0.0   

      Contagem de usuarios  Desenvolv

In [12]:
teste.describe()

Ano de lancamento  Classificacao  Contagem de criticas  \
count        4717.000000    4717.000000           4717.000000   
mean         1975.257367       1.227899             14.428238   
std           247.752416       1.388185             20.061530   
min             0.000000       0.000000              0.000000   
25%          2003.000000       0.000000              0.000000   
50%          2007.000000       1.000000              0.000000   
75%          2011.000000       3.000000             24.000000   
max          2017.000000       8.000000            107.000000   

       Contagem de usuarios  Desenvolvedora       Genero  Media de pontuacao  \
count           4717.000000     4717.000000  4717.000000         4717.000000   
mean              87.984312      206.959084     6.312911           19.331270   
std              444.607830      346.972354     3.448154           19.924709   
min                0.000000        0.000000     1.000000            0.000000   
25%                0.000000        0.000000     3.000000            0.000000   
50%                5.000000       23.000000     7.000000            4.150000   
75%               28.000000      276.000000     9.000000           39.750000   
max            10665.000000     1695.000000    12.000000           52.700000   

       Outras vendas   Plataforma  Pontuacao da critica  \
count    4717.000000  4717.000000           4717.000000   
mean        0.056010    10.030528             34.863261   
std         0.251452     5.921268             36.468859   
min         0.000000     1.000000              0.000000   
25%         0.000000     5.000000              0.000000   
50%         0.010000     8.000000              0.000000   
75%         0.040000    14.000000             72.000000   
max        10.570000    30.000000             97.000000   

       Pontuacao dos usuarios  Publicadora    Vendas EU    Vendas JP  \
count             4717.000000  4717.000000  4717.000000  4717.000000   
mean                 3.799279    61.912444     0.169347     0.095241   
std                  3.715898   103.823708     0.658819     0.333970   
min                  0.000000     0.000000     0.000000     0.000000   
25%                  0.000000     8.000000     0.000000     0.000000   
50%                  4.400000    16.000000     0.030000     0.000000   
75%                  7.600000    54.000000     0.130000     0.060000   
max                  9.600000   581.000000    28.960000     5.650000   

         Vendas NA  Vendas globais  Agrupamento  
count  4717.000000     4717.000000  4717.000000  
mean      0.295813        0.616519  1705.275175  
std       0.968660        1.938877  1439.541931  
min       0.000000        0.010000     4.000000  
25%       0.000000        0.070000   550.000000  
50%       0.080000        0.190000   857.000000  
75%       0.260000        0.540000  1949.000000  
max      41.360000       82.530000  4418.000000

In [13]:
a = teste['Agrupamento'].unique()

In [14]:
a.sort()
a

array([   4,    8,   14,   19,   20,   26,   43,   68,   81,  158,  159,
        246,  251,  324,  341,  342,  363,  404,  447,  455,  456,  540,
        550,  588,  648,  705,  799,  820,  828,  857,  960, 1103, 1177,
       1320, 1426, 1503, 1509, 1519, 1578, 1949, 2616, 2624, 3027, 3207,
       3499, 3698, 4248, 4418])

In [18]:
clusteringAffinityPropagation.predict([[15,9,2]])[0]

550

In [19]:
# for x in a:
#     print(teste[teste['Agrupamento']==x])
    
# teste[teste['Agrupamento']==4].groupby(by=['Media de pontuacao'])
teste[teste['Agrupamento']==550]

Ano de lancamento  Classificacao  Contagem de criticas  \
2                     0              2                  16.0   
3                  2006              0                   0.0   
9                  2010              0                   0.0   
10                 2010              2                  74.0   
15                 2010              0                   0.0   
20                 2015              0                   0.0   
28                 2012              0                   0.0   
30                 2004              0                   0.0   
32                 2015              0                   0.0   
34                 2012              0                   0.0   
40                 2012              0                   0.0   
42                 2006              1                  11.0   
46                 1997              0                   0.0   
48                 2008              0                   0.0   
55                 2013              1                   4.0   
58                 2005              0                   0.0   
62                 1997              0                   0.0   
67                 1998              0                   0.0   
85                 2012              0                   0.0   
106                2006              0                   0.0   
110                2016              2                  32.0   
117                2008              0                   0.0   
119                2015              0                   0.0   
125                2003              1                  29.0   
126                2007              0                   0.0   
134                2016              0                   0.0   
139                2015              0                   0.0   
146                2005              0                   0.0   
150                2006              0                   0.0   
155                2001              2                  34.0   
...                 ...            ...                   ...   
4612               2014              0                   0.0   
4615               2014              0                   0.0   
4622               2010              0                   0.0   
4625               2015              0                   0.0   
4627               2003              0                   0.0   
4631               2006              0                   0.0   
4634               1996              0                   0.0   
4636               2009              0                   0.0   
4637               2008              0                   0.0   
4639               1999              1                   9.0   
4641               2002              2                  24.0   
4647               2014              2                  66.0   
4655               2007              0                   0.0   
4660               2009              1                  10.0   
4661               2015              2                   0.0   
4666               2006              1                   0.0   
4671               2006              0                   0.0   
4672               2003              1                  22.0   
4685               2012              1                   9.0   
4686               1991              0                   0.0   
4688               2013              2                  82.0   
4696               2008              0                   0.0   
4697               1998              0                   0.0   
4700                  0              2                  33.0   
4703               2007              0                   0.0   
4704               2007              0                   0.0   
4708               2005              0                   0.0   
4709               2011              2                   7.0   
4710               2001              0                   0.0   
4714               2013              2                   5.0   

      Contagem de usuarios  Desenvolv