# Cluster Affinity Propagation

## Abrindo o arquivo limpo

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

data = pd.read_csv('fileCleaned.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6821 entries, 0 to 6820
Data columns (total 5 columns):
Platform        6821 non-null int64
Genre           6821 non-null int64
Global_Sales    6821 non-null float64
Rating          6821 non-null int64
Score_Mean      6821 non-null float64
dtypes: float64(2), int64(3)
memory usage: 266.5 KB


In [8]:
data.head()

Platform  Genre  Global_Sales  Rating  Score_Mean
0         0      0         82.53       0       42.00
1         0      2         35.52       0       45.15
2         0      0         32.77       0       44.00
3         3      1         29.80       0       48.75
4         0      5         28.92       0       32.30

In [2]:
from sklearn.cluster import AffinityPropagation
X = data
clusteringAffinityPropagation = AffinityPropagation().fit(X)

## Atributos do cluster

### cluster_centers_indices_

In [3]:
print(clusteringAffinityPropagation.cluster_centers_indices_)
print("Tamanho: " , len(clusteringAffinityPropagation.cluster_centers_indices_))

[   0    4    5   14   17   29   53   58   75  106  114  121  150  478
  492  579  810  858  929  934  971  974  985  987 1046 1126 1144 1148
 1274 1279 1280 1321 1329 1384 1406 1451 1488 1590 1618 1633 1667 1682
 1704 1742 1869 1931 1933 2053 2175 2192 2221 2243 2266 2267 2311 2346
 2377 2424 2481 2488 2526 2543 2666 2729 2735 2745 2770 2806 2830 2834
 2853 2885 2921 2953 3004 3081 3096 3244 3246 3273 3302 3317 3362 3412
 3449 3456 3467 3468 3613 3696 3753 3855 3912 3933 4015 4119 4171 4287
 4382 4400 4448 4655 4717 4764 4789 4794 4854 4903 5110 5142 5160 5170
 5361 5368 5423 5434 5492 5509 5519 5558 5620 5653 5702 5738 5745 5799
 5844 5929 6064 6105 6176 6211 6651 6656 6669 6693 6700 6757]
Tamanho:  138


### cluster_centers_

In [4]:
print(clusteringAffinityPropagation.cluster_centers_)
print("Tamanho: " , len(clusteringAffinityPropagation.cluster_centers_))

[[0.000e+00 0.000e+00 8.253e+01 0.000e+00 4.200e+01]
 [0.000e+00 5.000e+00 2.892e+01 0.000e+00 3.230e+01]
 [0.000e+00 1.000e+00 2.832e+01 0.000e+00 4.770e+01]
 [6.000e+00 8.000e+00 1.615e+01 1.000e+00 5.185e+01]
 [4.000e+00 6.000e+00 1.473e+01 1.000e+00 4.570e+01]
 [4.000e+00 6.000e+00 1.212e+01 1.000e+00 5.090e+01]
 [0.000e+00 5.000e+00 8.380e+00 0.000e+00 3.770e+01]
 [1.200e+01 3.000e+00 7.860e+00 2.000e+00 4.930e+01]
 [6.000e+00 2.000e+00 6.900e+00 0.000e+00 4.530e+01]
 [1.200e+01 8.000e+00 5.820e+00 1.000e+00 4.910e+01]
 [4.000e+00 2.000e+00 5.490e+00 0.000e+00 5.000e+01]
 [5.000e+00 6.000e+00 5.390e+00 1.000e+00 4.630e+01]
 [5.000e+00 8.000e+00 4.800e+00 1.000e+00 5.035e+01]
 [5.000e+00 8.000e+00 2.250e+00 1.000e+00 4.375e+01]
 [4.000e+00 5.000e+00 2.200e+00 2.000e+00 5.005e+01]
 [6.000e+00 0.000e+00 1.950e+00 0.000e+00 4.940e+01]
 [1.900e+01 9.000e+00 1.500e+00 2.000e+00 5.105e+01]
 [8.000e+00 1.000e+00 1.430e+00 0.000e+00 4.630e+01]
 [0.000e+00 8.000e+00 1.340e+00 2.000e+00 4.27

### labels_

In [5]:
print(clusteringAffinityPropagation.labels_)
print("Tamanho: " , len(clusteringAffinityPropagation.labels_))

[  0   2   2 ...  56 113 137]
Tamanho:  6821


### affinity_matrix_

In [6]:
print(clusteringAffinityPropagation.affinity_matrix_)
print("Tamanho: " , len(clusteringAffinityPropagation.affinity_matrix_))

[[   -0.     -2223.8626 -2480.0576 ... -7073.7904 -7119.5104 -7206.1104]
 [-2223.8626    -0.       -12.885  ... -1495.7826 -1615.0226 -1680.3626]
 [-2480.0576   -12.885     -0.     ... -1334.2576 -1421.5776 -1507.3776]
 ...
 [-7073.7904 -1495.7826 -1334.2576 ...    -0.      -113.16    -117.04  ]
 [-7119.5104 -1615.0226 -1421.5776 ...  -113.16      -0.       -26.04  ]
 [-7206.1104 -1680.3626 -1507.3776 ...  -117.04     -26.04      -0.    ]]
Tamanho:  6821


### n_iter_

In [7]:
print(clusteringAffinityPropagation.n_iter_)

100


## Predição

### Arbrindo arquivo com os dados originais

In [16]:
data = pd.read_csv('datasets/video-game-sales-with-ratings/Video_Games_Sales_as_at_22_Dec_2016.csv')
data.head()

Name Platform  Year_of_Release         Genre Publisher  \
0                Wii Sports      Wii           2006.0        Sports  Nintendo   
1         Super Mario Bros.      NES           1985.0      Platform  Nintendo   
2            Mario Kart Wii      Wii           2008.0        Racing  Nintendo   
3         Wii Sports Resort      Wii           2009.0        Sports  Nintendo   
4  Pokemon Red/Pokemon Blue       GB           1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  Critic_Score  \
0     41.36     28.96      3.77         8.45         82.53          76.0   
1     29.08      3.58      6.81         0.77         40.24           NaN   
2     15.68     12.76      3.79         3.29         35.52          82.0   
3     15.61     10.93      3.28         2.95         32.77          80.0   
4     11.27      8.89     10.22         1.00         31.37           NaN   

   Critic_Count User_Score  User_Count Developer Rating  
0          51.0          8       322.0  Nintendo      E  
1           NaN        NaN         NaN       NaN    NaN  
2          73.0        8.3       709.0  Nintendo      E  
3          73.0          8       192.0  Nintendo      E  
4           NaN        NaN         NaN       NaN    NaN

In [15]:
x = [[3,1,29.80,0,48.75],[3,5,28.92,0,40.00]]
clusteringAffinityPropagation.predict(x)

array([2, 1])

In [ ]:
def predicao(x):
    clusteringAffinityPropagation.predict(x)
data['Cluster'] = data.apply(lambda row: predicao(row['Critic_Score'], row['User_Score']), axis=1)