# Cluster Affinity Propagation

## Abrindo o arquivo de treino

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

treino = pd.read_csv('treino.csv')
treino.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9575 entries, 0 to 9574
Data columns (total 2 columns):
Genero        9575 non-null int64
Plataforma    9575 non-null int64
dtypes: int64(2)
memory usage: 149.7 KB


In [2]:
treino.head()

Genero  Plataforma
0       8           6
1      10          12
2       6           4
3       3           4
4       3          16

## Treinando o modelo

In [3]:
from sklearn.cluster import AffinityPropagation
clusteringAffinityPropagation = AffinityPropagation(max_iter=600).fit(treino)

## Atributos do cluster

### cluster_centers_indices_

In [4]:
print(clusteringAffinityPropagation.cluster_centers_indices_)
print("Tamanho: " , len(clusteringAffinityPropagation.cluster_centers_indices_))

[   0    1    4 ... 9569 9570 9574]
Tamanho:  5455


### cluster_centers_

In [5]:
print(clusteringAffinityPropagation.cluster_centers_)
print("Tamanho: " , len(clusteringAffinityPropagation.cluster_centers_))

[[ 8  6]
 [10 12]
 [ 3 16]
 ...
 [11 12]
 [ 8  4]
 [ 9  5]]
Tamanho:  5455


### labels_

In [6]:
print(clusteringAffinityPropagation.labels_)
print("Tamanho: " , len(clusteringAffinityPropagation.labels_))

[   0    1 4813 ... 1312 2512 5454]
Tamanho:  9575


### affinity_matrix_

In [7]:
print(clusteringAffinityPropagation.affinity_matrix_)
print("Tamanho: " , len(clusteringAffinityPropagation.affinity_matrix_))

[[  -0.  -40.   -8. ...  -81.  -89.   -2.]
 [ -40.   -0.  -80. ...  -13. -221.  -50.]
 [  -8.  -80.   -0. ... -125.  -45.  -10.]
 ...
 [ -81.  -13. -125. ...   -0. -260. -101.]
 [ -89. -221.  -45. ... -260.   -0.  -97.]
 [  -2.  -50.  -10. ... -101.  -97.   -0.]]
Tamanho:  9575


### n_iter_

In [8]:
print(clusteringAffinityPropagation.n_iter_)

600


# Predição

### Abrindo arquivo de teste

In [9]:
teste = pd.read_csv('teste.csv')
teste.head()

Ano de lancamento  Classificacao  Contagem de criticas  \
0                NaN            2.0                  19.0   
1             2008.0            3.0                  11.0   
2                NaN            1.0                  16.0   
3             2006.0            NaN                   NaN   
4             2007.0            0.0                  21.0   

   Contagem de usuarios  Desenvolvedora  Genero  Media de pontuacao  \
0                  12.0           250.0       3               30.25   
1                   6.0           260.0      10               32.90   
2                1096.0           189.0       8               42.00   
3                   NaN             NaN      10                 NaN   
4                  11.0          1397.0       4               38.75   

                                  Nome  Outras vendas  Plataforma  \
0                         Virtua Quest           0.00          19   
1                                 Bolt           0.02           5   
2                         Dead Space 3           0.02          14   
3  Kamaitachi no Yoru 2: Tokubetsu Hen           0.00          16   
4                    Nervous Brickdown           0.00           3   

   Pontuacao da critica  Pontuacao dos usuarios  Publicadora  Vendas EU  \
0                  55.0                     5.5         53.0       0.00   
1                  59.0                     6.8         32.0       0.04   
2                  78.0                     6.0          7.0       0.16   
3                   NaN                     NaN        120.0       0.00   
4                  70.0                     7.5         21.0       0.01   

   Vendas JP  Vendas NA  Vendas globais  
0       0.00       0.01            0.01  
1       0.00       0.12            0.19  
2       0.00       0.02            0.19  
3       0.01       0.00            0.01  
4       0.00       0.00            0.02

### Fazendo a predição

In [10]:
def predicao(x):
    return clusteringAffinityPropagation.predict([x])[0]
teste['Agrupamento'] = teste.apply(lambda row: predicao([row['Plataforma'], row['Genero']]), axis=1)

In [11]:
teste

Ano de lancamento  Classificacao  Contagem de criticas  \
0                   NaN            2.0                  19.0   
1                2008.0            3.0                  11.0   
2                   NaN            1.0                  16.0   
3                2006.0            NaN                   NaN   
4                2007.0            0.0                  21.0   
5                2001.0            0.0                  16.0   
6                2010.0            NaN                   NaN   
7                1998.0            NaN                   NaN   
8                2002.0            0.0                  24.0   
9                2010.0            NaN                   NaN   
10               2010.0            1.0                  74.0   
11               1995.0            NaN                   NaN   
12               1999.0            NaN                   NaN   
13               2008.0            2.0                  61.0   
14               2010.0            0.0                   5.0   
15               2010.0            NaN                   NaN   
16               2015.0            NaN                   NaN   
17               1994.0            NaN                   NaN   
18               2012.0            NaN                   NaN   
19               2011.0            NaN                   NaN   
20               2015.0            NaN                   NaN   
21               2007.0            2.0                  42.0   
22                  NaN            2.0                  49.0   
23               2010.0            3.0                   6.0   
24               2005.0            0.0                   NaN   
25               2007.0            0.0                  19.0   
26               2010.0            2.0                  11.0   
27               2005.0            3.0                  22.0   
28               2012.0            NaN                   NaN   
29               2006.0            3.0                   7.0   
...                 ...            ...                   ...   
4687             2006.0            0.0                  30.0   
4688             2013.0            1.0                  82.0   
4689             2012.0            3.0                  44.0   
4690             2011.0            2.0                   4.0   
4691             2004.0            0.0                  20.0   
4692             2008.0            NaN                   NaN   
4693             2006.0            2.0                  19.0   
4694             2005.0            2.0                  54.0   
4695             1997.0            NaN                   NaN   
4696             2008.0            NaN                   NaN   
4697             1998.0            NaN                   NaN   
4698             2006.0            3.0                  26.0   
4699             2003.0            2.0                  24.0   
4700                NaN            1.0                  33.0   
4701             1994.0            NaN                   NaN   
4702             2011.0            NaN                   NaN   
4703             2007.0            NaN                   NaN   
4704             2007.0            NaN                   NaN   
4705             2003.0            2.0                  26.0   
4706             2014.0            3.0                   4.0   
4707             2002.0            2.0                  23.0   
4708             2005.0            NaN                   NaN   
4709             2011.0            1.0                   7.0   
4710             2001.0            NaN                   NaN   
4711             1998.0            NaN                   NaN   
4712                NaN            2.0                  26.0   
4713             2004.0            0.0                  35.0   
4714             2013.0            1.0                   5.0   
4715             2009.0            NaN                   NaN   
4716             2011.0            NaN                   NaN   

      Contagem de usuarios  Desenvolv

In [12]:
teste.describe()

Ano de lancamento  Classificacao  Contagem de criticas  \
count        4644.000000    2518.000000           2340.000000   
mean         2006.306848       1.300238             29.084615   
std             6.174952       1.069128             19.621703   
min          1980.000000       0.000000              3.000000   
25%          2003.000000       0.000000             14.000000   
50%          2007.000000       1.000000             24.000000   
75%          2011.000000       2.000000             39.000000   
max          2017.000000       7.000000            107.000000   

       Contagem de usuarios  Desenvolvedora       Genero  Media de pontuacao  \
count           2516.000000     2551.000000  4717.000000         2329.000000   
mean             164.953100      381.683653     5.312911           38.718227   
std              598.306708      394.178954     3.448154            7.363114   
min                4.000000        0.000000     0.000000           10.150000   
25%               10.000000       74.000000     2.000000           34.450000   
50%               24.000000      243.000000     6.000000           39.850000   
75%               81.000000      565.000000     8.000000           44.050000   
max            10665.000000     1694.000000    11.000000           52.700000   

       Outras vendas   Plataforma  Pontuacao da critica  \
count    4717.000000  4717.000000           2340.000000   
mean        0.056010     9.030528             70.277778   
std         0.251452     5.921268             13.843587   
min         0.000000     0.000000             19.000000   
25%         0.000000     4.000000             62.000000   
50%         0.010000     7.000000             72.000000   
75%         0.040000    13.000000             80.000000   
max        10.570000    29.000000             97.000000   

       Pontuacao dos usuarios  Publicadora    Vendas EU    Vendas JP  \
count             2516.000000  4704.000000  4717.000000  4717.000000   
mean                 7.122893    61.083546     0.169347     0.095241   
std                  1.486172   103.915994     0.658819     0.333970   
min                  0.300000     0.000000     0.000000     0.000000   
25%                  6.400000     7.000000     0.000000     0.000000   
50%                  7.500000    15.000000     0.030000     0.000000   
75%                  8.200000    53.000000     0.130000     0.060000   
max                  9.600000   580.000000    28.960000     5.650000   

         Vendas NA  Vendas globais  Agrupamento  
count  4717.000000     4717.000000  4717.000000  
mean      0.295813        0.616519   717.826161  
std       0.968660        1.938877   852.199791  
min       0.000000        0.010000     0.000000  
25%       0.000000        0.070000    82.000000  
50%       0.080000        0.190000   631.000000  
75%       0.260000        0.540000   952.000000  
max      41.360000       82.530000  4653.000000

In [13]:
a = teste['Agrupamento'].unique()

In [14]:
a.sort()
a

array([   0,    1,    3,    5,    6,    7,    8,    9,   11,   12,   16,
         17,   21,   22,   23,   24,   31,   35,   36,   40,   48,   50,
         60,   61,   63,   71,   74,   75,   77,   81,   82,   86,   87,
         88,   90,   97,   99,  103,  104,  107,  111,  121,  122,  124,
        146,  149,  169,  177,  182,  188,  193,  196,  198,  212,  214,
        215,  262,  301,  325,  337,  356,  358,  362,  364,  365,  369,
        370,  376,  397,  417,  422,  457,  471,  631,  670,  732,  819,
        827,  830,  862,  915,  918,  941,  952,  986,  992, 1013, 1093,
       1106, 1180, 1193, 1480, 1527, 1538, 1569, 1610, 1626, 1799, 2055,
       2198, 2268, 2321, 2358, 2879, 2997, 3079, 3191, 3224, 3508, 3516,
       3700, 3756, 4483, 4653])

### Fazendo a predição de uma lista de jogos

In [49]:
# Plataforma - Gênero - Classificação
# SOCOM: U.S. Navy SEALs Fireteam Bravo 3 - [16,6]
# Dragon Ball Z: Budokai 2 - [19,9]
# Ultra Street Fighter IV - [9,9]
# Final Fantasy XI: Treasures of Aht Urhgan - [6,3]
clusteringAffinityPropagation.predict([[16,6]])

array([61])

In [52]:
# resultado = teste[teste['Agrupamento']==61].append(teste[teste['Agrupamento']==1610], ignore_index=True)
resultado = teste[teste['Agrupamento']==61]
resultado
# resultado.sort_values(by=['Ano de lancamento'], ascending=False)

Ano de lancamento  Classificacao  Contagem de criticas  \
16               2015.0            NaN                   NaN   
87                  NaN            1.0                  84.0   
113              1998.0            NaN                   NaN   
148              1998.0            NaN                   NaN   
154              2011.0            2.0                  38.0   
156              2004.0            2.0                  45.0   
191              2013.0            2.0                  17.0   
299              2004.0            2.0                  55.0   
422              2007.0            1.0                  40.0   
519              2002.0            2.0                  27.0   
581              2005.0            NaN                   NaN   
643              2006.0            2.0                  48.0   
659              1996.0            NaN                   NaN   
736              1997.0            NaN                   NaN   
754              2013.0            1.0                   5.0   
761              2005.0            1.0                  31.0   
780              2004.0            1.0                   9.0   
784              2001.0            NaN                   NaN   
801              2002.0            1.0                  25.0   
821              1995.0            NaN                   NaN   
853              2004.0            2.0                  11.0   
899              2004.0            1.0                  47.0   
947              1981.0            NaN                   NaN   
955              2011.0            1.0                  34.0   
991              1995.0            NaN                   NaN   
999              2005.0            2.0                  55.0   
1061             2004.0            2.0                  53.0   
1118                NaN            2.0                  24.0   
1143             2014.0            1.0                  55.0   
1166             2001.0            1.0                  24.0   
...                 ...            ...                   ...   
3947             2011.0            1.0                  32.0   
3967             2010.0            1.0                  23.0   
3997             2003.0            2.0                  11.0   
4016             2004.0            NaN                   NaN   
4020             1996.0            NaN                   NaN   
4028             1998.0            2.0                  17.0   
4055             1981.0            NaN                   NaN   
4056             2005.0            1.0                  13.0   
4069             2005.0            1.0                  18.0   
4076             1998.0            NaN                   NaN   
4127             1996.0            NaN                   NaN   
4140             2016.0            3.0                  82.0   
4211             2011.0            1.0                  48.0   
4217             1999.0            NaN                   NaN   
4226             2003.0            2.0                  19.0   
4227             1999.0            NaN                   NaN   
4270             2016.0            2.0                  20.0   
4277             1995.0            NaN                   NaN   
4279             2003.0            1.0                  50.0   
4299             2005.0            2.0                  46.0   
4321             2006.0            1.0                  19.0   
4348             2013.0            1.0                  47.0   
4370             2000.0            NaN                   NaN   
4508             2013.0            1.0                   6.0   
4528             1995.0            NaN                   NaN   
4576             2003.0            1.0                  33.0   
4584             2007.0            2.0                  20.0   
4620             2002.0            1.0                  23.0   
4621             2002.0            2.0                  28.0   
4626             2003.0            1.0                  38.0   

      Contagem de usuarios  Desenvolv

In [61]:
# from sklearn.metrics.pairwise import cosine_similarity

# z = [[resultado.iloc[0]['Genero'],resultado.iloc[0]['Plataforma']]]
# w = [[resultado.iloc[3]['Genero'],resultado.iloc[3]['Plataforma']]]
# print(cosine_similarity(z,w)[0][0])

option = [17,6]

def similaridade(x):
#     print(cosine_similarity([option],[x])[0][0]/10)
    return cosine_similarity([option],[x])[0][0]
resultado['Similaridade'] = resultado.apply(lambda row: similaridade([row['Plataforma'], row['Genero']]), axis=1)
resultado.sort_values(by=['Similaridade'], ascending=False)

/home/jackson/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':


Ano de lancamento  Classificacao  Contagem de criticas  \
16               2015.0            NaN                   NaN   
3821             2014.0            1.0                  15.0   
1665             2014.0            2.0                  11.0   
1782             2016.0            1.0                  17.0   
2519             2014.0            1.0                  69.0   
2701             2016.0            1.0                  33.0   
1452             2015.0            1.0                  74.0   
4270             2016.0            2.0                  20.0   
2936             2012.0            1.0                  31.0   
754              2013.0            1.0                   5.0   
4508             2013.0            1.0                   6.0   
4140             2016.0            3.0                  82.0   
4584             2007.0            2.0                  20.0   
3222             2007.0            2.0                  20.0   
4321             2006.0            1.0                  19.0   
3397             2005.0            1.0                  26.0   
3943             2006.0            0.0                  45.0   
2253             2002.0            2.0                  11.0   
1496             2004.0            1.0                  18.0   
1551             2003.0            2.0                  30.0   
4620             2002.0            1.0                  23.0   
1738             2002.0            1.0                  16.0   
3997             2003.0            2.0                  11.0   
2173             2003.0            0.0                  52.0   
2451             2005.0            2.0                  28.0   
1450             2005.0            1.0                  32.0   
2587             2002.0            2.0                  17.0   
2685             2005.0            2.0                  59.0   
3799             2004.0            2.0                  11.0   
2833             2004.0            1.0                  11.0   
...                 ...            ...                   ...   
1248             2000.0            1.0                  12.0   
4277             1995.0            NaN                   NaN   
1357             1997.0            0.0                   7.0   
113              1998.0            NaN                   NaN   
4127             1996.0            NaN                   NaN   
1582             1994.0            NaN                   NaN   
1231             1996.0            NaN                   NaN   
3113             1995.0            NaN                   NaN   
991              1995.0            NaN                   NaN   
4028             1998.0            2.0                  17.0   
2082             1998.0            NaN                   NaN   
3043             1997.0            NaN                   NaN   
3255             1998.0            NaN                   NaN   
3305             1994.0            NaN                   NaN   
2709             2001.0            2.0                   9.0   
821              1995.0            NaN                   NaN   
2665             1996.0            NaN                   NaN   
3527             1997.0            NaN                   NaN   
3558             2000.0            2.0                   8.0   
784              2001.0            NaN                   NaN   
2486             1998.0            0.0                   5.0   
659              1996.0            NaN                   NaN   
3872             1997.0            NaN                   NaN   
2424             1995.0            NaN                   NaN   
3080             1999.0            NaN                   NaN   
2149             2000.0            NaN                   NaN   
1686             2000.0            NaN                   NaN   
4217             1999.0            NaN                   NaN   
148              1998.0            NaN                   NaN   
2532             1999.0            NaN                   NaN   

      Contagem de usuarios  Desenvolv

In [18]:
# for x in a:
#     print(teste[teste['Agrupamento']==x].count())
    
# teste[teste['Agrupamento']==4].groupby(by=['Media de pontuacao'])

print(teste[teste['Agrupamento']==61].count())

Ano de lancamento         167
Classificacao             121
Contagem de criticas      121
Contagem de usuarios      121
Desenvolvedora            122
Genero                    170
Media de pontuacao        121
Nome                      170
Outras vendas             170
Plataforma                170
Pontuacao da critica      121
Pontuacao dos usuarios    121
Publicadora               170
Vendas EU                 170
Vendas JP                 170
Vendas NA                 170
Vendas globais            170
Agrupamento               170
dtype: int64
