# Cluster Affinity Propagation

## Abrindo o arquivo de treino

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

treino = pd.read_csv('treino.csv')
treino.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9575 entries, 0 to 9574
Data columns (total 2 columns):
Genero        9575 non-null int64
Plataforma    9575 non-null int64
dtypes: int64(2)
memory usage: 149.7 KB


In [2]:
treino.head()

Genero  Plataforma
0       8           6
1      10          12
2       6           4
3       3           4
4       3          16

## Treinando o modelo

In [3]:
from sklearn.cluster import AffinityPropagation
clusteringAffinityPropagation = AffinityPropagation(max_iter=600).fit(treino)

## Atributos do cluster

### cluster_centers_indices_

In [4]:
print(clusteringAffinityPropagation.cluster_centers_indices_)
print("Tamanho: " , len(clusteringAffinityPropagation.cluster_centers_indices_))

[   0    1    4 ... 9569 9570 9574]
Tamanho:  5455


### cluster_centers_

In [5]:
print(clusteringAffinityPropagation.cluster_centers_)
print("Tamanho: " , len(clusteringAffinityPropagation.cluster_centers_))

[[ 8  6]
 [10 12]
 [ 3 16]
 ...
 [11 12]
 [ 8  4]
 [ 9  5]]
Tamanho:  5455


### labels_

In [6]:
print(clusteringAffinityPropagation.labels_)
print("Tamanho: " , len(clusteringAffinityPropagation.labels_))

[   0    1 4813 ... 1312 2512 5454]
Tamanho:  9575


### affinity_matrix_

In [7]:
print(clusteringAffinityPropagation.affinity_matrix_)
print("Tamanho: " , len(clusteringAffinityPropagation.affinity_matrix_))

[[  -0.  -40.   -8. ...  -81.  -89.   -2.]
 [ -40.   -0.  -80. ...  -13. -221.  -50.]
 [  -8.  -80.   -0. ... -125.  -45.  -10.]
 ...
 [ -81.  -13. -125. ...   -0. -260. -101.]
 [ -89. -221.  -45. ... -260.   -0.  -97.]
 [  -2.  -50.  -10. ... -101.  -97.   -0.]]
Tamanho:  9575


### n_iter_

In [8]:
print(clusteringAffinityPropagation.n_iter_)

600


# Predição

### Abrindo arquivo de teste

In [9]:
teste = pd.read_csv('teste.csv')
teste.head()

Ano de lancamento  Classificacao  Contagem de criticas  \
0                NaN            2.0                  19.0   
1             2008.0            3.0                  11.0   
2                NaN            1.0                  16.0   
3             2006.0            NaN                   NaN   
4             2007.0            0.0                  21.0   

   Contagem de usuarios  Desenvolvedora  Genero  Media de pontuacao  \
0                  12.0           250.0       3               30.25   
1                   6.0           260.0      10               32.90   
2                1096.0           189.0       8               42.00   
3                   NaN             NaN      10                 NaN   
4                  11.0          1397.0       4               38.75   

                                  Nome  Outras vendas  Plataforma  \
0                         Virtua Quest           0.00          19   
1                                 Bolt           0.02           5   
2                         Dead Space 3           0.02          14   
3  Kamaitachi no Yoru 2: Tokubetsu Hen           0.00          16   
4                    Nervous Brickdown           0.00           3   

   Pontuacao da critica  Pontuacao dos usuarios  Publicadora  Vendas EU  \
0                  55.0                     5.5         53.0       0.00   
1                  59.0                     6.8         32.0       0.04   
2                  78.0                     6.0          7.0       0.16   
3                   NaN                     NaN        120.0       0.00   
4                  70.0                     7.5         21.0       0.01   

   Vendas JP  Vendas NA  Vendas globais  
0       0.00       0.01            0.01  
1       0.00       0.12            0.19  
2       0.00       0.02            0.19  
3       0.01       0.00            0.01  
4       0.00       0.00            0.02

### Criando uma nova coluna para o agrupamento

In [10]:
def predicao(x):
    return clusteringAffinityPropagation.predict([x])[0]
teste['Agrupamento'] = teste.apply(lambda row: predicao([row['Plataforma'], row['Genero']]), axis=1)

In [11]:
teste

Ano de lancamento  Classificacao  Contagem de criticas  \
0                   NaN            2.0                  19.0   
1                2008.0            3.0                  11.0   
2                   NaN            1.0                  16.0   
3                2006.0            NaN                   NaN   
4                2007.0            0.0                  21.0   
5                2001.0            0.0                  16.0   
6                2010.0            NaN                   NaN   
7                1998.0            NaN                   NaN   
8                2002.0            0.0                  24.0   
9                2010.0            NaN                   NaN   
10               2010.0            1.0                  74.0   
11               1995.0            NaN                   NaN   
12               1999.0            NaN                   NaN   
13               2008.0            2.0                  61.0   
14               2010.0            0.0                   5.0   
15               2010.0            NaN                   NaN   
16               2015.0            NaN                   NaN   
17               1994.0            NaN                   NaN   
18               2012.0            NaN                   NaN   
19               2011.0            NaN                   NaN   
20               2015.0            NaN                   NaN   
21               2007.0            2.0                  42.0   
22                  NaN            2.0                  49.0   
23               2010.0            3.0                   6.0   
24               2005.0            0.0                   NaN   
25               2007.0            0.0                  19.0   
26               2010.0            2.0                  11.0   
27               2005.0            3.0                  22.0   
28               2012.0            NaN                   NaN   
29               2006.0            3.0                   7.0   
...                 ...            ...                   ...   
4687             2006.0            0.0                  30.0   
4688             2013.0            1.0                  82.0   
4689             2012.0            3.0                  44.0   
4690             2011.0            2.0                   4.0   
4691             2004.0            0.0                  20.0   
4692             2008.0            NaN                   NaN   
4693             2006.0            2.0                  19.0   
4694             2005.0            2.0                  54.0   
4695             1997.0            NaN                   NaN   
4696             2008.0            NaN                   NaN   
4697             1998.0            NaN                   NaN   
4698             2006.0            3.0                  26.0   
4699             2003.0            2.0                  24.0   
4700                NaN            1.0                  33.0   
4701             1994.0            NaN                   NaN   
4702             2011.0            NaN                   NaN   
4703             2007.0            NaN                   NaN   
4704             2007.0            NaN                   NaN   
4705             2003.0            2.0                  26.0   
4706             2014.0            3.0                   4.0   
4707             2002.0            2.0                  23.0   
4708             2005.0            NaN                   NaN   
4709             2011.0            1.0                   7.0   
4710             2001.0            NaN                   NaN   
4711             1998.0            NaN                   NaN   
4712                NaN            2.0                  26.0   
4713             2004.0            0.0                  35.0   
4714             2013.0            1.0                   5.0   
4715             2009.0            NaN                   NaN   
4716             2011.0            NaN                   NaN   

      Contagem de usuarios  Desenvolv

In [12]:
teste.describe()

Ano de lancamento  Classificacao  Contagem de criticas  \
count        4644.000000    2518.000000           2340.000000   
mean         2006.306848       1.300238             29.084615   
std             6.174952       1.069128             19.621703   
min          1980.000000       0.000000              3.000000   
25%          2003.000000       0.000000             14.000000   
50%          2007.000000       1.000000             24.000000   
75%          2011.000000       2.000000             39.000000   
max          2017.000000       7.000000            107.000000   

       Contagem de usuarios  Desenvolvedora       Genero  Media de pontuacao  \
count           2516.000000     2551.000000  4717.000000         2329.000000   
mean             164.953100      381.683653     5.312911           38.718227   
std              598.306708      394.178954     3.448154            7.363114   
min                4.000000        0.000000     0.000000           10.150000   
25%               10.000000       74.000000     2.000000           34.450000   
50%               24.000000      243.000000     6.000000           39.850000   
75%               81.000000      565.000000     8.000000           44.050000   
max            10665.000000     1694.000000    11.000000           52.700000   

       Outras vendas   Plataforma  Pontuacao da critica  \
count    4717.000000  4717.000000           2340.000000   
mean        0.056010     9.030528             70.277778   
std         0.251452     5.921268             13.843587   
min         0.000000     0.000000             19.000000   
25%         0.000000     4.000000             62.000000   
50%         0.010000     7.000000             72.000000   
75%         0.040000    13.000000             80.000000   
max        10.570000    29.000000             97.000000   

       Pontuacao dos usuarios  Publicadora    Vendas EU    Vendas JP  \
count             2516.000000  4704.000000  4717.000000  4717.000000   
mean                 7.122893    61.083546     0.169347     0.095241   
std                  1.486172   103.915994     0.658819     0.333970   
min                  0.300000     0.000000     0.000000     0.000000   
25%                  6.400000     7.000000     0.000000     0.000000   
50%                  7.500000    15.000000     0.030000     0.000000   
75%                  8.200000    53.000000     0.130000     0.060000   
max                  9.600000   580.000000    28.960000     5.650000   

         Vendas NA  Vendas globais  Agrupamento  
count  4717.000000     4717.000000  4717.000000  
mean      0.295813        0.616519   717.826161  
std       0.968660        1.938877   852.199791  
min       0.000000        0.010000     0.000000  
25%       0.000000        0.070000    82.000000  
50%       0.080000        0.190000   631.000000  
75%       0.260000        0.540000   952.000000  
max      41.360000       82.530000  4653.000000

In [13]:
a = teste['Agrupamento'].unique()

In [14]:
a.sort()
a

array([   0,    1,    3,    5,    6,    7,    8,    9,   11,   12,   16,
         17,   21,   22,   23,   24,   31,   35,   36,   40,   48,   50,
         60,   61,   63,   71,   74,   75,   77,   81,   82,   86,   87,
         88,   90,   97,   99,  103,  104,  107,  111,  121,  122,  124,
        146,  149,  169,  177,  182,  188,  193,  196,  198,  212,  214,
        215,  262,  301,  325,  337,  356,  358,  362,  364,  365,  369,
        370,  376,  397,  417,  422,  457,  471,  631,  670,  732,  819,
        827,  830,  862,  915,  918,  941,  952,  986,  992, 1013, 1093,
       1106, 1180, 1193, 1480, 1527, 1538, 1569, 1610, 1626, 1799, 2055,
       2198, 2268, 2321, 2358, 2879, 2997, 3079, 3191, 3224, 3508, 3516,
       3700, 3756, 4483, 4653])

In [25]:
# Plataforma - Gênero - Classificação
# SOCOM: U.S. Navy SEALs Fireteam Bravo 3 - [16,6]
# Dragon Ball Z: Budokai 2 - [19,9]
# Ultra Street Fighter IV - [9,9]
# Final Fantasy XI: Treasures of Aht Urhgan - [6,3]
clusteringAffinityPropagation.predict([[9,9],[6,3]])

array([ 370, 1610])

In [42]:
resultado = teste[teste['Agrupamento']==370].append(teste[teste['Agrupamento']==1610], ignore_index=True)
resultado.sort_values(by=['Ano de lancamento'], ascending=False)

Ano de lancamento  Classificacao  Contagem de criticas  \
7              2016.0            2.0                  21.0   
1              2016.0            2.0                  60.0   
4              2015.0            2.0                  28.0   
5              2015.0            NaN                   NaN   
3              2014.0            NaN                   NaN   
6              2014.0            NaN                   NaN   
0              2012.0            NaN                   NaN   
2              2011.0            2.0                  69.0   
20             2008.0            3.0                  20.0   
15             2007.0            NaN                   NaN   
41             2007.0            NaN                   NaN   
28             2007.0            NaN                   NaN   
29             2007.0            NaN                   NaN   
32             2007.0            NaN                   NaN   
36             2007.0            NaN                   NaN   
23             2007.0            1.0                  25.0   
69             2007.0            NaN                   NaN   
56             2007.0            NaN                   NaN   
52             2006.0            2.0                  18.0   
54             2006.0            NaN                   NaN   
48             2006.0            NaN                   NaN   
45             2006.0            NaN                   NaN   
42             2006.0            NaN                   NaN   
62             2006.0            NaN                   NaN   
66             2006.0            NaN                   NaN   
68             2006.0            2.0                  54.0   
13             2006.0            2.0                  45.0   
24             2005.0            2.0                  38.0   
37             2005.0            2.0                  35.0   
26             2005.0            2.0                  41.0   
..                ...            ...                   ...   
70             2004.0            2.0                  44.0   
9              2004.0            NaN                   NaN   
38             2004.0            2.0                  21.0   
33             2004.0            2.0                  14.0   
34             2003.0            1.0                  55.0   
31             2003.0            2.0                  19.0   
30             2003.0            2.0                  16.0   
22             2002.0            2.0                  47.0   
14             2002.0            2.0                  16.0   
16             2002.0            NaN                   NaN   
18             2002.0            NaN                   NaN   
19             2002.0            2.0                  35.0   
57             2002.0            0.0                  46.0   
27             2002.0            2.0                  20.0   
53             2002.0            2.0                  30.0   
49             2002.0            2.0                  23.0   
39             2002.0            2.0                  26.0   
58             2001.0            2.0                  23.0   
25             2001.0            2.0                  13.0   
65             2001.0            2.0                  14.0   
44             2001.0            2.0                   9.0   
40             2001.0            2.0                  21.0   
43             2000.0            2.0                  12.0   
59             2000.0            2.0                  13.0   
60             2000.0            2.0                  27.0   
21             2000.0            2.0                  16.0   
50             2000.0            NaN                   NaN   
8                 NaN            2.0                  49.0   
46                NaN            2.0                  23.0   
47                NaN            NaN                   NaN   

    Contagem de usuarios  Desenvolvedora  Genero  Media de pontuacao  \
7                   39.0           496.0       9               46.30   
1              

In [21]:
# for x in a:
#     print(teste[teste['Agrupamento']==x].count())
    
# teste[teste['Agrupamento']==4].groupby(by=['Media de pontuacao'])

print(teste[teste['Agrupamento']==631].count())

Ano de lancamento         107
Classificacao              42
Contagem de criticas       39
Contagem de usuarios       42
Desenvolvedora             42
Genero                    109
Media de pontuacao         39
Nome                      109
Outras vendas             109
Plataforma                109
Pontuacao da critica       39
Pontuacao dos usuarios     42
Publicadora               109
Vendas EU                 109
Vendas JP                 109
Vendas NA                 109
Vendas globais            109
Agrupamento               109
dtype: int64
