# Importando as bibliotecas e o dataset

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

data = pd.read_csv('datasets/video-game-sales-with-ratings/Video_Games_Sales_as_at_22_Dec_2016.csv')
data.head()

Name Platform  Year_of_Release         Genre Publisher  \
0                Wii Sports      Wii           2006.0        Sports  Nintendo   
1         Super Mario Bros.      NES           1985.0      Platform  Nintendo   
2            Mario Kart Wii      Wii           2008.0        Racing  Nintendo   
3         Wii Sports Resort      Wii           2009.0        Sports  Nintendo   
4  Pokemon Red/Pokemon Blue       GB           1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  Critic_Score  \
0     41.36     28.96      3.77         8.45         82.53          76.0   
1     29.08      3.58      6.81         0.77         40.24           NaN   
2     15.68     12.76      3.79         3.29         35.52          82.0   
3     15.61     10.93      3.28         2.95         32.77          80.0   
4     11.27      8.89     10.22         1.00         31.37           NaN   

   Critic_Count User_Score  User_Count Developer Rating  
0          51.0          8       322.0  Nintendo      E  
1           NaN        NaN         NaN       NaN    NaN  
2          73.0        8.3       709.0  Nintendo      E  
3          73.0          8       192.0  Nintendo      E  
4           NaN        NaN         NaN       NaN    NaN

## Informações do dataset

### Estatísticas descritivas

In [2]:
data.describe()

Year_of_Release      NA_Sales      EU_Sales      JP_Sales  \
count     16450.000000  16719.000000  16719.000000  16719.000000   
mean       2006.487356      0.263330      0.145025      0.077602   
std           5.878995      0.813514      0.503283      0.308818   
min        1980.000000      0.000000      0.000000      0.000000   
25%        2003.000000      0.000000      0.000000      0.000000   
50%        2007.000000      0.080000      0.020000      0.000000   
75%        2010.000000      0.240000      0.110000      0.040000   
max        2020.000000     41.360000     28.960000     10.220000   

        Other_Sales  Global_Sales  Critic_Score  Critic_Count    User_Count  
count  16719.000000  16719.000000   8137.000000   8137.000000   7590.000000  
mean       0.047332      0.533543     68.967679     26.360821    162.229908  
std        0.186710      1.547935     13.938165     18.980495    561.282326  
min        0.000000      0.010000     13.000000      3.000000      4.000000  
25%        0.000000      0.060000     60.000000     12.000000     10.000000  
50%        0.010000      0.170000     71.000000     21.000000     24.000000  
75%        0.030000      0.470000     79.000000     36.000000     81.000000  
max       10.570000     82.530000     98.000000    113.000000  10665.000000

### Informações gerais

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 16 columns):
Name               16717 non-null object
Platform           16719 non-null object
Year_of_Release    16450 non-null float64
Genre              16717 non-null object
Publisher          16665 non-null object
NA_Sales           16719 non-null float64
EU_Sales           16719 non-null float64
JP_Sales           16719 non-null float64
Other_Sales        16719 non-null float64
Global_Sales       16719 non-null float64
Critic_Score       8137 non-null float64
Critic_Count       8137 non-null float64
User_Score         10015 non-null object
User_Count         7590 non-null float64
Developer          10096 non-null object
Rating             9950 non-null object
dtypes: float64(9), object(7)
memory usage: 2.0+ MB


### Coluna 'Genre' e seus respectivos índices

In [4]:
#0      Sports
#1      Platform
#2      Racing
#3      Role-Playing
#4      Puzzle
#5      Misc
#6      Shooter
#7      Simulation
#8      Action
#9      Fighting
#10     Adventure
#11     Strategy

### Coluna 'Platform' e seus respectivos índices

In [5]:
#0      Wii
#1      NES
#2      GB
#3      DS
#4      X360
#5      PS3
#6      PS2
#7      SNES
#8      GBA
#9      PS4
#10     3DS
#11     N64
#12     PS
#13     XB
#14     PC
#15     2600
#16     PSP
#17     XOne
#19     WiiU
#20     GC
#21     GEN
#22     DC
#23     PSV
#24     SAT
#25     SCD
#26     WS
#27     NG
#28     TG16
#29     3DO
#30     GG
#31     PCFX

### Coluna 'Rating' e seus respectivos índices

In [6]:
#0      E
#1      M
#2      T
#3      E10+
#4      K-A
#5      AO
#6      EC
#7      RP

### Anotações imediatas

A princípio penso em focar nas colunas Genre, Platform, Global_Sales, Critic_Score, User_Score e Rating.

## Limpando os dados

### Alterando valores da coluna Genre

In [7]:
generos = data['Genre'].copy()
generos[generos== 'Sports'] =0
generos[generos== 'Platform'] =1
generos[generos== 'Racing'] =2
generos[generos== 'Role-Playing'] =3
generos[generos== 'Puzzle'] =4
generos[generos== 'Misc'] =5
generos[generos== 'Shooter'] =6
generos[generos== 'Simulation'] =7
generos[generos== 'Action'] =8
generos[generos== 'Fighting'] =9
generos[generos== 'Adventure'] =10
generos[generos== 'Strategy'] =11
data['Genre'] = generos

### Alterando valores da coluna Platform

In [8]:
x = data['Platform'].copy()
x[x== 'Wii'] =0
x[x== 'NES'] =1
x[x== 'GB'] =2
x[x== 'DS'] =3
x[x== 'X360'] =4
x[x== 'PS3'] =5
x[x== 'PS2'] =6
x[x== 'SNES'] =7
x[x== 'GBA'] =8
x[x== 'PS4'] =9
x[x== '3DS'] =10
x[x== 'N64'] =11
x[x== 'PS'] =12
x[x== 'XB'] =13
x[x== 'PC'] =14
x[x== '2600'] =15
x[x== 'PSP'] =16
x[x== 'XOne'] =17
x[x== 'WiiU'] =18
x[x== 'GC'] =19
x[x== 'GENc'] =20
x[x== 'DC'] =21
x[x== 'PSV'] =22
x[x== 'SAT'] =23
x[x== 'SCD'] =24
x[x== 'WS'] =25
x[x== 'NG'] =26
x[x== 'TG16'] =27
x[x== '3DO'] =28
x[x== 'GG'] =29
x[x== 'PCFX'] =30
data['Platform'] = x

### Alterando valores da coluna Rating

In [9]:
x = data['Rating'].copy()
x[x== 'E'] =0
x[x== 'M'] =1
x[x== 'T'] =2
x[x== 'E10+'] =3
x[x== 'K-A'] =4
x[x== 'AO'] =5
x[x== 'EC'] =6
x[x== 'RP'] =7
data['Rating'] = x

### Retirando os valores TBD e valores NaN

In [10]:
data = data[data['User_Score'] != 'tbd']
data['Score_Mean'] = 0.0
#data['Score_Mean'].astype('float64') = 0.0
data = data.dropna()

### Retirando os valores 'tbd' da coluna User_Score

In [11]:
data = data[data['User_Score'] != 'tbd']
#data['Critic_Score'].astype('float64')
#data['User_Score'].astype('float64')
#data['Score_Mean'].astype('float64')

### Salvando arquivo

In [12]:
fileCleaned = pd.DataFrame(data={'Platform': data['Platform'], 'Genre': data['Genre'], 'Global_Sales': data['Global_Sales'],
     'Critic_Score': data['Critic_Score'], 'User_Score': data['User_Score'], 'Rating': data['Rating'], 'Score_Mean': data['Score_Mean']})
fileCleaned.dropna().to_csv(r'fileCleaned.csv', sep=',', index=False)

### Abrindo arquivo novamente

In [13]:
data = pd.read_csv('fileCleaned.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6825 entries, 0 to 6824
Data columns (total 7 columns):
Platform        6825 non-null int64
Genre           6825 non-null int64
Global_Sales    6825 non-null float64
Critic_Score    6825 non-null float64
User_Score      6825 non-null float64
Rating          6825 non-null int64
Score_Mean      6825 non-null float64
dtypes: float64(4), int64(3)
memory usage: 373.3 KB


### Criando um DataFrame só com os valores importantes

In [14]:
def media(x, y):
    return (x+y)/2
data['Score_Mean'] = data.apply(lambda row: media(row['Critic_Score'], row['User_Score']), axis=1)
data = pd.DataFrame(data={'Platform': data['Platform'], 'Genre': data['Genre'], 'Global_Sales': data['Global_Sales'],
     'Rating': data['Rating'], 'Score_Mean': data['Score_Mean']})

### Retirando valores duplicados

In [15]:
data = data.drop_duplicates()
data.dropna().to_csv(r'fileCleaned.csv', sep=',', index=False)
data.head()

Platform  Genre  Global_Sales  Rating  Score_Mean
0         0      0         82.53       0       42.00
1         0      2         35.52       0       45.15
2         0      0         32.77       0       44.00
3         3      1         29.80       0       48.75
4         0      5         28.92       0       32.30

# Treinando os modelos de clusterização

## Cluster Affinity Propagation

### Abrindo o arquivo limpo

In [16]:
data = pd.read_csv('fileCleaned.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6821 entries, 0 to 6820
Data columns (total 5 columns):
Platform        6821 non-null int64
Genre           6821 non-null int64
Global_Sales    6821 non-null float64
Rating          6821 non-null int64
Score_Mean      6821 non-null float64
dtypes: float64(2), int64(3)
memory usage: 266.5 KB


In [17]:
from sklearn.cluster import AffinityPropagation
X = data
clusteringAffinityPropagation = AffinityPropagation().fit(X)

### Atributos do cluster

In [18]:
print(clusteringAffinityPropagation.cluster_centers_indices_)
print("Tamanho: " , len(clusteringAffinityPropagation.cluster_centers_indices_))

[   0    4    5   14   17   29   53   58   75  106  114  121  150  478
  492  579  810  858  929  934  971  974  985  987 1046 1126 1144 1148
 1274 1279 1280 1321 1329 1384 1406 1451 1488 1590 1618 1633 1667 1682
 1704 1742 1869 1931 1933 2053 2175 2192 2221 2243 2266 2267 2311 2346
 2377 2424 2481 2488 2526 2543 2666 2729 2735 2745 2770 2806 2830 2834
 2853 2885 2921 2953 3004 3081 3096 3244 3246 3273 3302 3317 3362 3412
 3449 3456 3467 3468 3613 3696 3753 3855 3912 3933 4015 4119 4171 4287
 4382 4400 4448 4655 4717 4764 4789 4794 4854 4903 5110 5142 5160 5170
 5361 5368 5423 5434 5492 5509 5519 5558 5620 5653 5702 5738 5745 5799
 5844 5929 6064 6105 6176 6211 6651 6656 6669 6693 6700 6757]
Tamanho:  138


In [19]:
print(clusteringAffinityPropagation.cluster_centers_)
print("Tamanho: " , len(clusteringAffinityPropagation.cluster_centers_))

[[0.000e+00 0.000e+00 8.253e+01 0.000e+00 4.200e+01]
 [0.000e+00 5.000e+00 2.892e+01 0.000e+00 3.230e+01]
 [0.000e+00 1.000e+00 2.832e+01 0.000e+00 4.770e+01]
 [6.000e+00 8.000e+00 1.615e+01 1.000e+00 5.185e+01]
 [4.000e+00 6.000e+00 1.473e+01 1.000e+00 4.570e+01]
 [4.000e+00 6.000e+00 1.212e+01 1.000e+00 5.090e+01]
 [0.000e+00 5.000e+00 8.380e+00 0.000e+00 3.770e+01]
 [1.200e+01 3.000e+00 7.860e+00 2.000e+00 4.930e+01]
 [6.000e+00 2.000e+00 6.900e+00 0.000e+00 4.530e+01]
 [1.200e+01 8.000e+00 5.820e+00 1.000e+00 4.910e+01]
 [4.000e+00 2.000e+00 5.490e+00 0.000e+00 5.000e+01]
 [5.000e+00 6.000e+00 5.390e+00 1.000e+00 4.630e+01]
 [5.000e+00 8.000e+00 4.800e+00 1.000e+00 5.035e+01]
 [5.000e+00 8.000e+00 2.250e+00 1.000e+00 4.375e+01]
 [4.000e+00 5.000e+00 2.200e+00 2.000e+00 5.005e+01]
 [6.000e+00 0.000e+00 1.950e+00 0.000e+00 4.940e+01]
 [1.900e+01 9.000e+00 1.500e+00 2.000e+00 5.105e+01]
 [8.000e+00 1.000e+00 1.430e+00 0.000e+00 4.630e+01]
 [0.000e+00 8.000e+00 1.340e+00 2.000e+00 4.27

In [20]:
print(clusteringAffinityPropagation.labels_)
print("Tamanho: " , len(clusteringAffinityPropagation.labels_))

[  0   2   2 ...  56 113 137]
Tamanho:  6821


In [21]:
print(clusteringAffinityPropagation.affinity_matrix_)
print("Tamanho: " , len(clusteringAffinityPropagation.affinity_matrix_))

[[   -0.     -2223.8626 -2480.0576 ... -7073.7904 -7119.5104 -7206.1104]
 [-2223.8626    -0.       -12.885  ... -1495.7826 -1615.0226 -1680.3626]
 [-2480.0576   -12.885     -0.     ... -1334.2576 -1421.5776 -1507.3776]
 ...
 [-7073.7904 -1495.7826 -1334.2576 ...    -0.      -113.16    -117.04  ]
 [-7119.5104 -1615.0226 -1421.5776 ...  -113.16      -0.       -26.04  ]
 [-7206.1104 -1680.3626 -1507.3776 ...  -117.04     -26.04      -0.    ]]
Tamanho:  6821


In [22]:
print(clusteringAffinityPropagation.n_iter_)

100


In [23]:
data.head()

Platform  Genre  Global_Sales  Rating  Score_Mean
0         0      0         82.53       0       42.00
1         0      2         35.52       0       45.15
2         0      0         32.77       0       44.00
3         3      1         29.80       0       48.75
4         0      5         28.92       0       32.30

### Predict

In [24]:
def predizer(x):
    return clusteringAffinityPropagation.predict([[x['Platform'],x['Genre'],x['Global_Sales'],x['Rating'],x['Score_Mean']]])[0]
data['Cluster'] = data.apply(lambda row: predizer(row), axis=1)

In [25]:
data

Platform  Genre  Global_Sales  Rating  Score_Mean  Cluster
0            0      0         82.53       0       42.00        0
1            0      2         35.52       0       45.15        2
2            0      0         32.77       0       44.00        2
3            3      1         29.80       0       48.75        2
4            0      5         28.92       0       32.30        1
5            0      1         28.32       0       47.70        2
6            3      2         23.21       0       49.80        2
7            0      0         22.70       0       43.85        2
8            4      5         21.81       0       33.65        1
9            0      0         21.79       0       43.70        2
10           5      8         21.04       1       52.60        3
11           6      8         20.81       1       52.00        3
12           3      5         20.15       0       42.45        4
13           4      8         16.27       1       52.55        3
14           6      8         16.15       1       51.85        3
15           3      4         15.29       0       42.05        4
16           6      2         14.98       0       51.70        5
17           4      6         14.73       1       45.70        4
18           4      6         14.61       1       46.65        4
19           5      6         13.79       1       44.15        4
20           4      6         13.67       1       43.90        4
21           4      6         13.47       1       50.15        5
22           5      6         13.32       1       45.60        4
23           6      8         13.10       1       52.75        3
24           0      9         12.84       2       50.95        5
25          10      2         12.66       0       46.60        7
26           5      6         12.63       1       47.20        4
27           9      8         12.61       1       52.65        3
28           3      7         12.13       0       47.35        4
29           4      6         12.12       1       50.90        5
...        ...    ...           ...     ...         ...      ...
6791        14      2          0.01       0       42.95       52
6792        18      5          0.01       0       45.15       67
6793        14      3          0.01       2       45.65       78
6794         9      3          0.01       2       34.45      129
6795        14      0          0.01       0       42.45       52
6796         3      3          0.01       2       31.45       82
6797         9      8          0.01       1       28.25      104
6798        14     10          0.01       1       30.35      135
6799        14      6          0.01       1       35.25      128
6800        14      8          0.01       3       33.00      113
6801         8      0          0.01       2       43.75       41
6802        14      2          0.01       0       40.80       79
6803        19      4          0.01       0       36.00       85
6804        16     11          0.01       3       38.45      136
6805        14      3          0.01       2       45.30       78
6806        14      8          0.01       2       42.95       56
6807         6      2          0.01       0       35.40      118
6808        17      8          0.01       1       35.50       95
6809         4      9          0.01       2       25.55       77
6810        14      8          0.01       1       39.35       93
6811        14      8          0.01       3       44.10       56
6812         8      2          0.01       0       45.25       17
6813        17      2          0.01       0       35.60       85
6814        14     11          0.01       3       27.40      135
6815        18      8          0.01       0       44.75       67
6816         8      8          0.01       0       24.20      104
6817         8      9          0.01       1       44.90       26
6818        14      8          0.01       1       43.80       56
6819        14      6          0.01       2       33.40      113
6820        14     11          0.01      

In [26]:
data[data['Cluster']==122]

Platform  Genre  Global_Sales  Rating  Score_Mean  Cluster
856          4      2          1.43       0       28.50      122
1194         4      2          1.09       0       24.55      122
1261         4      1          1.04       3       25.20      122
1349         3      2          0.97       0       28.05      122
1466         6      1          0.90       2       28.25      122
1685         3      2          0.77       0       25.95      122
1822         4      3          0.70       1       27.75      122
1935         6      2          0.65       2       26.50      122
1958         4      0          0.64       2       27.00      122
2020         6      0          0.62       0       27.40      122
2028         4      1          0.62       0       28.15      122
2049         4      0          0.61       3       24.50      122
2064         6      1          0.60       3       25.50      122
2704         5      3          0.43       2       26.00      122
2752         6      2          0.42       2       27.25      122
2763         3      1          0.42       0       25.40      122
2849         5      1          0.40       0       28.00      122
2927         6      0          0.38       0       27.80      122
3056         6      2          0.36       2       25.15      122
3126         5      0          0.34       0       24.65      122
3282         5      0          0.32       0       27.80      122
3464         6      2          0.28       0       28.15      122
3590         4      0          0.27       0       24.20      122
3594         3      2          0.27       0       25.55      122
3615         6      2          0.26       0       28.30      122
3632         6      0          0.26       2       25.35      122
3672         6      0          0.25       0       25.30      122
3675         4      3          0.25       1       28.60      122
3739         6      3          0.24       3       25.50      122
3812         5      3          0.24       1       29.25      122
...        ...    ...           ...     ...         ...      ...
5198         5      1          0.11       3       28.90      122
5284         6      1          0.10       3       28.10      122
5300         4      0          0.10       0       26.05      122
5303         6      1          0.10       3       28.50      122
5382         4      0          0.09       0       26.25      122
5410         3      3          0.09       3       26.80      122
5425         3      3          0.09       2       26.55      122
5451         3      3          0.09       2       26.50      122
5452         5      3          0.09       2       24.30      122
5462         6      3          0.09       2       29.30      122
5522         6      3          0.08       2       27.15      122
5564         3      1          0.08       3       27.25      122
5598         5      1          0.08       3       27.05      122
5600         6      3          0.08       2       24.85      122
5619         4      1          0.08       3       27.05      122
5637         5      0          0.08       0       27.75      122
5702         5      2          0.07       1       27.00      122
5739         4      3          0.07       1       26.50      122
5752         4      0          0.07       0       25.80      122
5769         3      3          0.07       0       27.75      122
5826         4      2          0.07       3       27.80      122
5839         4      3          0.06       1       24.20      122
5897         4      2          0.06       0       26.40      122
6056         4      3          0.05       1       27.55      122
6102         6      2          0.05       0       28.55      122
6155         4      0          0.05       0       24.10      122
6205         3      0          0.04       0       25.25      122
6311         3      4          0.04       0       27.40      122
6364         4      0          0.03       0       24.50      122
6515         6      2          0.02      